name: Python Tests

on:
  push:
    branches:
      - master  # Trigger workflow on push to the 'master' branch
  pull_request:
    branches:
      - master  # Trigger workflow on pull requests targeting the 'master' branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11  # Use Python 3.11

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip  # Upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Run Pytest
      - name: Run tests
        run: |
          pytest tests/
